/**
 * merge-schema.js
 * 
 * Concatenates all modular .prisma files from the modules/ directory
 * into a single schema.prisma that Prisma can process.
 * 
 * Usage: node prisma/merge-schema.js
 * 
 * This script should always run BEFORE:
 *   - prisma generate (`npx prisma generate`)
 *   - prisma db push (`npx prisma db push`)
 *   - prisma migrate dev
 * 
 * Conventions:
 *   - 00-header.prisma  → Generator & Datasource (always placed first)
 *   01-xx, 02-xx, ...   → Module files sorted numerically
 * 
 * Safety:
 *   - Validates no duplicate model or enum names across modules
 *   - Header file is required (script exits if missing)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MODULES_DIR = path.join(__dirname, 'modules');
const HEADER_FILE = path.join(MODULES_DIR, '00-header.prisma');
const OUTPUT_FILE = path.join(__dirname, 'schema.prisma');

/**
 * Validate modules directory.
 */
if (!fs.existsSync(MODULES_DIR)) {
    console.error(`❌ Modules directory not found: ${MODULES_DIR}`);
    console.error('   Run: mkdir prisma/modules');
    process.exit(1);
}

/**
 * Validate header file exists.
 * The header contains the required `generator` and `datasource` blocks.
 */
if (!fs.existsSync(HEADER_FILE)) {
    console.error(`❌ Header file not found: ${HEADER_FILE}`);
    console.error('   Create prisma/modules/00-header.prisma first.');
    process.exit(1);
}

/**
 * Read all .prisma module files (excluding header).
 * Numeric sorting ensures proper ordering (09 before 10).
 */
const moduleFiles = fs
    .readdirSync(MODULES_DIR)
    .filter(file => file.endsWith('.prisma') && file !== '00-header.prisma')
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

if (moduleFiles.length === 0) {
    console.error('❌ No .prisma module files found in modules directory.');
    console.error('   (00-header.prisma alone is not enough — add at least one module.)');
    process.exit(1);
}

// ====================================================================
// Validation: Check for duplicate model and enum names
// ====================================================================
const modelNames = new Map();   // modelName → fileName
const enumNames = new Map();    // enumName → fileName
const modelRegex = /^\s*model\s+(\w+)\s*\{/gm;
const enumRegex = /^\s*enum\s+(\w+)\s*\{/gm;

function extractNames(content, regex, nameMap, typeLabel, fileName) {
    let match;
    while ((match = regex.exec(content)) !== null) {
        const name = match[1];
        if (nameMap.has(name)) {
            console.error(`❌ Duplicate ${typeLabel} name "${name}" found in:`);
            console.error(`   - ${nameMap.get(name)}`);
            console.error(`   - ${fileName}`);
            process.exit(1);
        }
        nameMap.set(name, fileName);
    }
}

for (const file of [...moduleFiles, '00-header.prisma']) {
    const filePath = path.join(MODULES_DIR, file);
    const content = fs.readFileSync(filePath, 'utf8');

    extractNames(content, modelRegex, modelNames, 'model', file);
    extractNames(content, enumRegex, enumNames, 'enum', file);
}

// ====================================================================
// Build merged content
// ====================================================================

/**
 * Header for generated schema.
 */
let combined = `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ------------------------------------------------------------
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Generated by:
 *   node prisma/merge-schema.js
 *
 * Source modules:
 *   prisma/modules/*.prisma
 * ============================================================
 */

`;

/**
 * 1. Add header (00-header.prisma) — generator + datasource blocks.
 */
const headerContent = fs.readFileSync(HEADER_FILE, 'utf8').trim();
combined += headerContent;
combined += '\n\n';

/**
 * 2. Add each module file in order.
 */
for (const file of moduleFiles) {
    const filePath = path.join(MODULES_DIR, file);
    const content = fs.readFileSync(filePath, 'utf8').trim();

    combined += `// ============================================================\n`;
    combined += `// Module: ${file}\n`;
    combined += `// ============================================================\n\n`;

    combined += content;
    combined += '\n\n';
}

/**
 * Remove old generated schema (if exists) and write new one.
 */
if (fs.existsSync(OUTPUT_FILE)) {
    fs.unlinkSync(OUTPUT_FILE);
}

fs.writeFileSync(
    OUTPUT_FILE,
    combined.trimEnd() + '\n',
    'utf8'
);

// ====================================================================
// Summary
// ====================================================================
console.log('==============================================');
console.log(' ✅ Prisma schema merged successfully');
console.log('==============================================');
console.log(`   Modules : ${moduleFiles.length}`);
console.log(`   Models  : ${modelNames.size}`);
console.log(`   Enums   : ${enumNames.size}`);
console.log(`   Output  : ${OUTPUT_FILE}`);
console.log('==============================================');