/**
 * merge-schema.js
 * 
 * Concatenates all modular .prisma files from the modules/ directory
 * into a single schema.prisma that Prisma can process.
 * 
 * Usage: node prisma/merge-schema.js
 * 
 * This script should always run BEFORE:
 *   - prisma generate (`npx prisma generate`)
 *   - prisma db push (`npx prisma db push`)
 *   - prisma migrate dev
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MODULES_DIR = path.join(__dirname, 'modules');
const OUTPUT_FILE = path.join(__dirname, 'schema.prisma');

/**
 * Validate modules directory.
 */
if (!fs.existsSync(MODULES_DIR)) {
    console.error(`❌ Modules directory not found: ${MODULES_DIR}`);
    process.exit(1);
}

/**
 * Read all .prisma module files.
 * Numeric sorting ensures:
 * 09-xxx.prisma
 * 10-xxx.prisma
 * instead of alphabetical ordering.
 */
const moduleFiles = fs
    .readdirSync(MODULES_DIR)
    .filter(file => file.endsWith('.prisma'))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

if (moduleFiles.length === 0) {
    console.error('❌ No .prisma files found in modules directory.');
    process.exit(1);
}
/**
 * Header for generated schema.
 */
let combined = `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ------------------------------------------------------------
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Generated by:
 *   node prisma/merge-schema.js
 *
 * Source modules:
 *   prisma/modules/*.prisma
 * ============================================================
 */

`;

for (const file of moduleFiles) {
    const filePath = path.join(MODULES_DIR, file);
    const content = fs.readFileSync(filePath, 'utf8').trim();

    combined += `// ============================================================\n`;
    combined += `// Module: ${file}\n`;
    combined += `// ============================================================\n\n`;

    combined += content;
    combined += "\n\n";
}

/**
 * Remove old generated schema (if exists).
 */
if (fs.existsSync(OUTPUT_FILE)) {
    fs.unlinkSync(OUTPUT_FILE);
}

/**
 * Write merged schema.
 */
fs.writeFileSync(
    OUTPUT_FILE,
    combined.trimEnd() + "\n",
    'utf8'
);

console.log('==============================================');
console.log(' Prisma schema merged successfully');
console.log(` Modules : ${moduleFiles.length}`);
console.log(` Output  : ${OUTPUT_FILE}`);
console.log('==============================================');