export const eventSeeds = [
  {
    id: 1,
    title: 'Clean Beach Campaign',
    description: 'Join volunteers to clean Vung Tau beach and protect the coast.',
    shortDescription: 'Help clean up local beaches',
    image_url: 'https://example.com/event-beach.jpg',
    organization: { id: 3, name: 'Green Earth' },
    category: { id: 2, name: 'Environment' },
    skills: [{ id: 5, name: 'Physical fitness' }],
    start_date: '2026-07-01T08:00:00Z',
    end_date: '2026-07-01T12:00:00Z',
    location: 'Vung Tau Beach',
    max_capacity: 50,
    approved_participants: 23,
    status: 'PUBLISHED',
    is_active: true,
    deleted_at: null
  },
  {
    id: 2,
    title: 'Community Teaching Day',
    description: 'Teach basic English and math for children in the community.',
    shortDescription: 'Support weekend teaching activities',
    image_url: 'https://example.com/event-teaching.jpg',
    organization: { id: 4, name: 'Care for Kids' },
    category: { id: 4, name: 'Education' },
    skills: [{ id: 8, name: 'Teaching' }],
    start_date: '2026-07-05T09:00:00Z',
    end_date: '2026-07-05T16:00:00Z',
    location: 'Ho Chi Minh City',
    max_capacity: 30,
    approved_participants: 30,
    status: 'PUBLISHED',
    is_active: true,
    deleted_at: null
  },
  {
    id: 3,
    title: 'Green Park Tree Planting',
    description: 'Plant trees and restore public park green areas.',
    shortDescription: 'Plant trees with local volunteers',
    image_url: null,
    organization: { id: 3, name: 'Green Earth' },
    category: { id: 2, name: 'Environment' },
    skills: [{ id: 6, name: 'Gardening' }],
    start_date: '2026-07-10T07:30:00Z',
    end_date: '2026-07-10T11:30:00Z',
    location: 'Da Nang',
    max_capacity: 40,
    approved_participants: 12,
    status: 'PUBLISHED',
    is_active: true,
    deleted_at: null
  },
  {
    id: 4,
    title: 'Draft Food Drive',
    description: 'Draft event hidden from public discovery.',
    shortDescription: 'Draft hidden event',
    image_url: null,
    organization: { id: 5, name: 'Food Share' },
    category: { id: 6, name: 'Community' },
    skills: [],
    start_date: '2026-07-03T08:00:00Z',
    end_date: '2026-07-03T10:00:00Z',
    location: 'Ha Noi',
    max_capacity: 20,
    approved_participants: 0,
    status: 'DRAFT',
    is_active: true,
    deleted_at: null
  },
  {
    id: 5,
    title: 'Completed Health Support',
    description: 'Completed event hidden from public discovery MVP.',
    shortDescription: 'Completed hidden event',
    image_url: null,
    organization: { id: 6, name: 'Health Hands' },
    category: { id: 7, name: 'Healthcare' },
    skills: [{ id: 9, name: 'First Aid' }],
    start_date: '2026-06-01T08:00:00Z',
    end_date: '2026-06-01T12:00:00Z',
    location: 'Hue',
    max_capacity: 25,
    approved_participants: 20,
    status: 'COMPLETED',
    is_active: true,
    deleted_at: null
  },
  {
    id: 6,
    title: 'Inactive Environment Fair',
    description: 'Inactive event must not appear in public discovery.',
    shortDescription: 'Inactive hidden event',
    image_url: null,
    organization: { id: 3, name: 'Green Earth' },
    category: { id: 2, name: 'Environment' },
    skills: [{ id: 5, name: 'Physical fitness' }],
    start_date: '2026-07-20T08:00:00Z',
    end_date: '2026-07-20T12:00:00Z',
    location: 'Vung Tau Beach',
    max_capacity: 50,
    approved_participants: 10,
    status: 'PUBLISHED',
    is_active: false,
    deleted_at: null
  }
];
